---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: tagging
        uses: anothrNick/github-tag-action@1.59.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: master
          INITIAL_VERSION: 1.0.0
          DEFAULT_BUMP: none
          BRANCH_HISTORY: last
      - name: "Set up QEMU"
        if: steps.tagging.outputs.part
        uses: docker/setup-qemu-action@v3
      - name: "Set up Docker Buildx"
        if: steps.tagging.outputs.part
        uses: docker/setup-buildx-action@v3
      - name: "Login to ghcr.io"
        if: steps.tagging.outputs.part
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        if: steps.tagging.outputs.part
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/eumel8/k8s-sidecar:latest
            ghcr.io/eumel8/k8s-sidecar:${{ steps.tagging.outputs.tag }}
